## config cluster schema ##
clusters:
  - name: "cluster name"
    api_ip: "..."
    ingress_ip: "..."
    external_port: "<auto / device name>"
    network_api_port: "<auto / device name>"
    masters:
    - name: "A"
      type: "<vm / physical / bf>"
      node: ""
      ip: ""
    workers:
    - name: "A"
      type: "<vm / physical / bf>"
      ip: ""
      node: ""
      bmc_ip: "required if bmc ip address is not host ip + 1"
      bmc_user: "required if physical or bf"
      bmc_password: "required if physical or bf"
    # optionally describe additional node attributes
    hosts:
    - name: "A"
      images_path: "/path/to/pool/directory"
