apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
  "type": "dpu-cni",
  "cniVersion": "0.3.1",
  "name": "dpu-cni",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24"
  }
}'
