apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    grafana:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/master: ""
    openshiftStateMetrics:
      nodeSelector:
       node-role.kubernetes.io/master: ""
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/master: ""
