apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-dpu-operator-subscription
  namespace: openshift-operators
spec:
  channel: "stable"
  name: dpu-network-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
