name: Check Style

on:
  push:
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==22.12.0
        python -m pip install flake8
    - name: Black
      run: |
        black --check --diff .
    - name: flake8
      run: |
        flake8

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
        python -m pip install types-paramiko
        python -m pip install types-PyYAML
        python -m pip install types-requests
    - name: Run mypy
      run: mypy --strict cda.py --config-file mypy.ini
