name: Check Style

on:
  push:
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install black==22.12.0
        python -m pip install flake8
        python -m pip install flake8-comprehensions
        python -m pip install mypy
        python -m pip install types-paramiko
        python -m pip install types-PyYAML
        python -m pip install types-requests
        python -m pip install pytest
        python -m pip install aicli
        python -m pip install paramiko==2.12.0
        python -m pip install gitpython
        python -m pip install kubernetes
    - name: black
      run: |
        black --version
        black --check --diff .
    - name: flake8
      run: |
        flake8 --version
        flake8
    - name: mypy
      run: |
        mypy --version
        mypy --strict --config-file mypy.ini .
    - name: pytest
      # Tests may want to know whether they run under CI in github actions.
      #
      # For example, under normal conditions a test may autodetect that it
      # cannot pass due to some dependency missing and be skipped. If the same
      # test is known that it must(!) pass under CI, then such a skip must not
      # happen with CDA_GITHUB_CI=1.
      run: |
        pytest --version
        CDA_GITHUB_CI=1 pytest -v
